# Generated by Django 3.2.7 on 2021-10-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('times_in_day', models.FloatField(default=1)),
                ('repeat', models.CharField(choices=[
                 ('D', 'daily'), ('W', 'Weakly'), ('M', 'Mounthly')], default='D', max_length=1)),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='habits',
                                   to=settings.AUTH_USER_MODEL)),
                ('checking',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='habits',
                                   to='habits.check')),
            ],
        ),
    ]
