# Generated by Django 3.2.7 on 2021-10-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='checking',
        ),
        migrations.AddField(
            model_name='check',
            name='habit',
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checks',
                to='habits.habit'),
            preserve_default=False,
        ),
    ]
