# Generated by Django 3.2.7 on 2021-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20211006_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='times_in_day',
        ),
        migrations.AddField(
            model_name='habit',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
