# Generated by Django 3.2.7 on 2021-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20211008_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
