# Generated by Django 3.2.7 on 2021-10-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_is_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
