# Generated by Django 3.2.7 on 2021-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20211018_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='best_streak',
            field=models.IntegerField(default=0, verbose_name='Лучший стрик'),
        ),
    ]
