# Generated by Django 3.2.7 on 2021-11-01 16:36

import datetime
from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_best_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[habits.validators.date_validator]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='times_in_period',
            field=models.IntegerField(default=1, verbose_name='Количетсво повторений в период'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique habit for author'),
        ),
    ]
